### ISSUE TITLE
driver error

### ISSUE THREAD

**Issue by Envoy-VC** [EMAXthedestroyer/Projects#1]
chrome driver needs to be in path

**Comment by WaviestBalloon** [comment]
https://www.google.co.uk/search?q=chrome+driver+needs+to+be+in+path&oq=chrome+driver+needs+to+be+in+path
I'm unsure what you are talking about but here, this is what I think you're talking about: 
`driver = webdriver.Chrome('/pathchromedriver/') `

**Comment by EMAXthedestroyer** [comment]
### #download chromedriver
#create a folder named 'webdrivers' and move 'chromedriver.exe' into the folder
#then the code implementation:
  _PATH = 'webdrivers\chromedriver.exe'
  driver = webdriver.Chrome(PATH)_
### #the web driver we're using is chrome(given the path to the webdriver file)
