### ISSUE TITLE
Default Adapter Failed 

### ISSUE THREAD

**Issue by UvinduBro** [EMAXthedestroyer/Projects#13]
![image](https://user-images.githubusercontent.com/79355885/121810363-3873f080-cc7e-11eb-8a88-bc8809f377c1.png)

 When I try to Run Software 😥🤔

**Comment by EMAXthedestroyer** [comment]
Whenever a new version of chrome is released, the selenium chrome webdriver has to be updated

**Comment by EMAXthedestroyer** [comment]
can be found at https://chromedriver.chromium.org/
